### ISSUE TITLE
julia_setup() takes a lot of time

### ISSUE THREAD

**Issue by jabbalaci** [JuliaInterop/JuliaCall#175]
I'd like to use Julia in .Rmd files but the initialization is too slow. `julia_setup()` takes 44 seconds on my machine. Is that normal?

```
> library(JuliaCall)
> julia_setup()
Julia version 1.6.3 at location /usr/bin will be used.
Loading setup script for JuliaCall...
Finish loading setup script for JuliaCall.
>
```

I'm using Manjaro Linux.

**Comment by Non-Contradiction** [comment]
Does knit again also take a long time? 
The first time to use JuliaCall or use JuliaCall with a new version of julia will incur a long setup time. But the second time would be better. And the startup time should be improved with a newer version of julia. 
Generally, I would expect <20 seconds of startup time.

**Comment by ViralBShah** [comment]
Please reopen if still an issue (or file a new one).
