### ISSUE TITLE
Error Calling julia from R 

### ISSUE THREAD

**Issue by nataliemyers12** [JuliaInterop/JuliaCall#204]
Hi,

I have successfully run Julia Setup in R, but when I go to actually use Julia in R, I receive this error. I've tried a variety of steps to fix this, but have not been successful. Could anyone provide insight? I am using R 4.3.0 and Julia 1.8.5

Error: Error happens in Julia.
InitError: could not load library "/home/thomsonlab/.julia/artifacts/e4afa6442d82c9e3819067808b91aa8308d90db6/lib/libgeotiff.so"
libproj.so.25: cannot open shared object file: No such file or directory

Full:

> jl.inputs<- jl.prep(n.Pops=NROW(plhon),CS_Point.File=plhonsp,response=lower(as.matrix(gen.dist)),cholmod = TRUE, JULIA_HOME = JULIA_HOME) 
Error: Error happens in Julia.
InitError: could not load library "/home/thomsonlab/.julia/artifacts/e4afa6442d82c9e3819067808b91aa8308d90db6/lib/libgeotiff.so"
libproj.so.25: cannot open shared object file: No such file or directory
Stacktrace:
  [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
    @ Base.Libc.Libdl ./libdl.jl:117
  [2] dlopen(s::String, flags::UInt32)
    @ Base.Libc.Libdl ./libdl.jl:116
  [3] macro expansion
    @ ~/.julia/packages/JLLWrappers/QpMQW/src/products/library_generators.jl:54 [inlined]
  [4] __init__()
    @ libgeotiff_jll ~/.julia/packages/libgeotiff_jll/EG4x2/src/wrappers/x86_64-linux-gnu.jl:15
  [5] _include_from_serialized(pkg::Base.PkgId, path::String, depmods::Vector{Any})
    @ Base ./loading.jl:831
  [6] _tryrequire_from_serialized(modkey::Base.PkgId, path::String, sourcepath::String, depmods::Vector{Any})
    @ Base ./loading.jl:938
  [7] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, build_id::UInt64)
    @ Base ./loa

**Comment by ViralBShah** [comment]
Please reopen if still an issue (or file a new one).
