### ISSUE TITLE
Is JuliaCall still being maintained? 

### ISSUE THREAD

**Issue by enweg** [JuliaInterop/JuliaCall#208]
I have a package on CRAN that depends on JuliaCall and was recently contacted by CRAN to let me know that they cannot reach the maintainer of JuliaCall anymore. Is JuliaCall still being maintained?

**Comment by edwardlavender** [comment]
Are there any updates on this issue? I am also interested in the current status and plans for JuliaCall. It is a fantastic package, but there have been no commits for over a year and there are a number of open issues and pull requests. Has the package been abandoned or are there plans to continue package development in due course?

**Comment by palday** [comment]
@Non-Contradiction how would you feel about transferring ownership of the repo to JuliaInterop?

**Comment by cderv** [comment]
As part of discussion about future of this package, I just want to mention that in the ecosystem of Julia from R package, there is also this one: [stefan-m-lenz/JuliaConnectoR](https://github.com/stefan-m-lenz/JuliaConnectoR)

**Comment by JackDunnNZ** [comment]
To save others repeating the effort, I have attempted to contact @Non-Contradiction through email and linkedin to draw his attention to this issue

**Comment by JackDunnNZ** [comment]
> To save others repeating the effort, I have attempted to contact @Non-Contradiction through email and linkedin to draw his attention to this issue

And he replied letting me know he will take a look when he gets the chance 🎉
