### ISSUE TITLE
Suppress Julia setup messages

### ISSUE THREAD

**Issue by askhari139** [JuliaInterop/JuliaCall#222]
Is there any way to suppress the message that shows up when julia_setup is used? The message looks like this:

```
Julia version 1.10.0 at location C:\Programs\JULIA-~1.0\bin will be used.
Loading setup script for JuliaCall...
Finish loading setup script for JuliaCall.
```
The package is great though. Thank you very much for creating it.

**Comment by ViralBShah** [comment]
Solution discussed in https://github.com/JuliaInterop/JuliaCall/issues/233
