### ISSUE TITLE
julia_setup error in Rstudio

### ISSUE THREAD

**Issue by junjunlab** [JuliaInterop/JuliaCall#233]
Hi, I got this error in Rstudio, can anyone help me? Thanks!

![1724136822720](https://github.com/user-attachments/assets/20291bbc-0fed-4de2-80b2-3c73e554f79d)

**Comment by marc-milgrom-ncl** [comment]
Your Julia 1.9 install needs the Suppressor package installed. The simplest way is to launch the julia REPL with, in your case:
`/mnt/data/home/tycloud/.local/share/R/JuliaCall/julia/1.9.4/julia-1.9.4/bin/julia`
At the command prompt press "]" to enter pkg mode then:
`add Suppressor`
